"""Build production/shot_index.md: every shot of the film with its exact position (timecode in/out), scene, method,
characters, Arabic line, thumbnail, links to keyframe/clip, and status. Regenerate after every production session.
Usage: uv run --with pyyaml --with pillow python tools/shot_index.py   (writes renders/thumbs/<ID>.jpg too)"""
import json, sys
from pathlib import Path
from PIL import Image
sys.path.insert(0, str(Path(__file__).parent))
from common import ROOT, parts, iter_shots, tc

TH = ROOT / "renders/thumbs"


def thumb(sid):
    for e in ("jpg", "png"):
        src = ROOT / f"renders/keyframes/{sid}.{e}"
        if src.exists():
            dst = TH / f"{sid}.jpg"
            if not dst.exists() or dst.stat().st_mtime < src.stat().st_mtime:
                im = Image.open(src).convert("RGB"); w, h = im.size; ch = int(w * 9 / 16); top = int((h - ch) * 0.3)
                im.crop((0, top, w, top + ch)).resize((320, 180)).save(dst, quality=80)
            return f"../renders/keyframes/{sid}.{e}", f"../renders/thumbs/{sid}.jpg"
    return None, None


def main():
    TH.mkdir(parents=True, exist_ok=True)
    lines = {}
    lp = ROOT / "renders/audio/lines/part1_lines.json"
    if lp.exists(): lines = {l["shot"]: l for l in json.loads(lp.read_text())["lines"]}
    out = ["# فهرس اللقطات — Shot index", "",
           "مولَّد آليًا بـ `tools/shot_index.py` — لا تعدّله يدويًا. كل لقطة: موضعها في الفيلم (من–إلى)، المشهد، طريقة الإنتاج، الشخصيات، الجملة المنطوقة، الصورة المفتاحية، المقطع، والحالة.",
           "Auto-generated by `tools/shot_index.py` — do not edit by hand.", ""]
    t, counts = 0, {}
    for p in (1, 2):
        doc = parts()[p]; out += [f"## الجزء {p}", ""]
        for sc in doc["scenes"]:
            shots = sc.get("shots") or []
            if not shots:
                out += [f"### {sc['scene']} — {sc['title']} (لم تُكتب لقطاته بعد)", ""]; continue
            d = sum(s["dur"] for s in shots)
            out += [f"### {sc['scene']} — {sc['title']}  `{tc(t)}–{tc(t + d)}`", "",
                    "| # | الصورة | اللقطة | الموضع | المدة | الطريقة | الشخصيات | الصوت | المقطع | الحالة |", "|---|---|---|---|---|---|---|---|---|---|"]
            for i, sh in enumerate(shots, 1):
                kf, th = thumb(sh["id"]); clip = ROOT / f"renders/clips/{sh['id']}.mp4"
                img = f"[<img src=\"{th}\" width=\"200\">]({kf})" if th else ("رسوم HF" if sh["method"] == "HF" else "—")
                line = (sh.get("vo") and "راوية: " + sh["vo"]) or sh.get("dlg") or (sh.get("sfx") and "🔊 " + sh["sfx"]) or ""
                cl = f"[mp4](../renders/clips/{sh['id']}.mp4)" if clip.exists() else "—"
                st = sh["status"]; counts[st] = counts.get(st, 0) + 1
                out.append(f"| {i} | {img} | `{sh['id']}` | `{tc(t)}–{tc(t + sh['dur'])}` | {sh['dur']}ث | {sh['method']} | {', '.join(sh['chars']) or '—'} | {line.replace('|', '/')} | {cl} | {st} |")
                t += sh["dur"]
            out.append("")
    out[4:4] = ["**الإجمالي:** " + " · ".join(f"{k}: {v}" for k, v in sorted(counts.items())), ""]
    (ROOT / "production/shot_index.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote production/shot_index.md", counts)


if __name__ == "__main__":
    main()
